on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed pokedex URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://aqueous-anchorage-99787.herokuapp.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
